### ISSUE TITLE
XCode 10 Unable to import

### ISSUE THREAD

**Issue by yarodevuci** [wuqiong/mp3lame-for-iOS#6]
I tried drag and drop the framework
I tried pod install
And in the end i am unable to import it..

**Comment by Changzw** [comment]
you should change -mios-simulator-version-min=7.0 to -mios-simulator-version-min=8.0 in build-lame-framework.sh<br>
and use the new lame-framework to your project.

**Comment by yarodevuci** [comment]
got it
